apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ef21jn7lz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ef21jn7lz-python 
  name: ef21jn7lz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ef21jn7lz-python 
